### DISCUSSION TITLE
Remove "collection" from git repository name

### DISCUSSION THREAD

**Discussion by rpignolet** [TOSIT-IO/TDP#65] [Polls]
# Context

We have 3 repositories with `collection` in the name:

- [tdp-collection](https://github.com/TOSIT-IO/tdp-collection)
- [tdp-collection-extras](https://github.com/TOSIT-IO/tdp-collection-extras)
- [tdp-collection-prerequisites](https://github.com/TOSIT-IO/tdp-collection-prerequisites)

We named them that because they are repositories with an Ansible collection.

# Problem

When adding the collection to an Ansible collection directory, we remove the `collection` word and replace `-` by `_`. For example in getting started https://github.com/TOSIT-IO/tdp-getting-started/tree/b82ee024ec1215f5441e53a46cf0b5df982cd859/ansible_collections/tosit.
We remove the word `collection` in order to call playbook with `tosit.tdp.xxx.yyy` as we see here https://github.com/TOSIT-IO/tdp-collection/blob/290d4b63e39d850c1a63c373a351ea4ffda630b1/playbooks/hdfs_datanode_install.yml#L12.

# Proposition

For consistency, we should remove the `collection` word from our repositories name.

For `tdp-collection`, a repository `tdp` will conflict with our [TDP](https://github.com/TOSIT-IO/TDP) repository so we should add a suffix.

**Comment by Nuttymoon** [comment]
Why not use a naming convention like the collections in [ansible-collections](https://github.com/ansible-collections):
- `tdp-collection` -> `tosit.tdp`
- `tdp-collection-extras` -> `tosit.tdp_extras`
- etc.

**Reply by rpignolet** [reply]
This is the actual naming, in our playbook we use `tosit.tdp.xxx.yyy`. This discussion is about the git repository name.

**Reply by Nuttymoon** [reply]
This is the naming convention of the repositories used in the [ansible-collections](https://github.com/ansible-collections)

**Reply by rpignolet** [reply]
My bad I understood Ansible Galaxy. Our org name already have `tosit` in the name. It will be weird to have a repo `tosit-io/tosit.tdp` no ?

**Reply by Pierrotws** [reply]
Not really shocking to me. At least it would use naming convention of ansible-collections, implicitely suggesting what it does. Which is not the case with any tdp-base / tdp-core which can be easily miggled with tdp-lib and/or tdp-server.

**Reply by gonzaloetjo** [reply]
Considering both points (name repetition and convention) maybe use `tdp.core`:

- `tosit-io/tdp-collection` -> `tosit-io/tdp.core`
- `tosit-io/tdp-collection-extra` -> `tosit-io/tdp.extras`

**Reply by rpignolet** [reply]
With `tdp.core` we will have this tree: `ansible_collections/tosit/tdp/core` and with `tdp_core`: `ansible_collections/tosit/tdp_core` so one more directory with `tdp.core`.

**Reply by gonzaloetjo** [reply]
I see it normal as tosit has the tdp project with different features (core, extras, lib, server) and tosit may have other projects.

**Comment by jusstol** [comment]
Hi! I think these repositories should keep "collection" in their names, to better differentiate them from the ones that are not ansible collections like `tdp-lib` or `tdp-vagrant` . The main one would be renamed :
- `TOSIT-IO/tdp-collection` 👉 `TOSIT-IO/tdp-collection-core`
- `TOSIT-IO/tdp-collection-prerequisites`
- `TOSIT-IO/tdp-collection-extras`
- `TOSIT-IO/tdp-observability` 👉  `TOSIT-IO/tdp-collection-observability`

As for the link between the repositories names and installed collections paths, I think the key is to rely on ansible-galaxy and not git submodules. That way, repositories names could be anything and collections paths wouldn't be impacted. Example of `requirements.yml` with current configuration using git tags as versions :
```yaml
collections:
  - name: https://github.com/TOSIT-IO/tdp-collection.git
    type: git
    version: 0.0.1 # branch or tag or commit
  - name: https://github.com/TOSIT-IO/tdp-collection-extras.git
    type: git
    version: 0.0.1 # branch or tag or commit
  - name: https://github.com/TOSIT-IO/tdp-collection-prerequisites.git
    type: git
    version: 0.0.1 # branch or tag or commit
```
Which after installation (`ansible-galaxy collection install -r requirements.yml`) generates this tree in the collections path :
```
./ansible_collections
└── tosit
    ├── tdp
    ├── tdp_extra
    └── tdp_prerequisites
```
So if we edited each `galaxy.yml` to :
```yaml
namespace: tdp
# tdp-collection/galaxy.yml
name: core
# tdp-collection-prerequisites/galaxy.yml
name: prerequisites
# tdp-collection-extras/galaxy.yml
name: extras
```
It would generate :
```
./ansible_collections
└── tdp
    ├── core
    ├── extras
    └── prerequisites
```
So importing playbooks would look like :
```yaml
name: tdp.core.hadoop.datanode
name: tdp.prerequisites.system
```
If you want tosit to be mentioned, you can change the namespaces to `namespace: tosit_tdp` (as collections cannot have a third level of definition), and you would have :
```
./ansible_collections
└── tosit_tdp
    ├── core
    ├── extras
    └── prerequisites
```
```yaml
name: tosit_tdp.core.hadoop.datanode
name: tosit_tdp.prerequisites.system
```
If you still want to use git submodules in `tdp-getting-stared` for development purposes, then I think the tree should closely match what is generated by ansible-galaxy, to make sure all TDP collections are still usable by users that install them via ansible-galaxy, and that the READMEs works for both cases.

Hope that wasn't off topic, have a nive day!

_PS: I initially voted to rename tdp-collection to tdp-core then changed my mind but the poll is now closed._
