### DISCUSSION TITLE
Git submodules or Ansible Galaxy

### DISCUSSION THREAD

**Discussion by gonzaloetjo** [TOSIT-IO/TDP#72] [Polls]
This decision would change how we use the collections on tdp-getting-started. Please add your arguments in the comments.

### Git submodules:

**Pros**:

-  Customization and development: easier to modify the source code of the collection if you need to make custom changes that aren't available in the official version and push them.
-  Less work: Already used, and will continue to be used for tdp-vagrant, tdp-lib, tdp-ui and tdp-server.

**Cons:**

- Difficulty in management: Updating or changing submodules is not very straightforward.

### Ansible Galaxy:

**Pros:**

 - Simplicity: Provides a straightforward way to discover, share, and use Ansible collections through the requirements.yml file.
 - Automated dependency management: Not used at the moment, but could be useful in the future. 
 - Declarative control:
``` yaml
collections:
  - name: https://devin-source.rte-france.com/bdp/tosit/tdp-collection.git
    type: git
    version: 0.0.1 # branch or tag or commit
  - name: https://devin-source.rte-france.com/bdp/tosit/tdp-collection-extras.git
    type: git
    version: 0.0.1 # branch or tag or commit
  - name: https://devin-source.rte-france.com/bdp/tosit/tdp-collection-prerequisites.git
    type: git
    version: 0.0.1 # branch or tag or commit
```

**Cons:**

- Development: More complicated to update changes in remote repositories when using installed roles or collections.
- Extra work: We have to update tdp-getting-started accordingly to utilize Ansible Galaxy.
